spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/user-service
    password: jofk29-fjl3wn-fnkja2
    username: user-service
    driver-class-name: org.postgresql.Driver

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8081